
source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target "Shiji" do
platform :ios, '10.0'
pod 'HandyJSON', '~> 4.0.0-beta.1'
pod 'AlibcTradeSDK'
pod 'Alamofire', '~> 4.5'
pod 'MJRefresh'
pod 'Kingfisher', '~> 4.5’
end




